### ISSUE TITLE
Docker-compose envar declaration shouldn't use quotation marks

### ISSUE THREAD

**Issue by sjaks** [basiliski/discordbot#6]
As shown here: https://docs.docker.com/compose/environment-variables/ I am a dumbass and pushed erroneous code to master. The token variable should be declared like

```
version: "3"
services:
  discord_bot:
    build: .
    environment:
      - DC_TOKEN=waaaaaaaaaaaaaaaaaaa
```
